### ISSUE TITLE
Allow consumers to specify a list of CIDRs for bastion access

### ISSUE THREAD

**Issue by liafizan** [oracle-terraform-modules/terraform-oci-bastion#29]
### Description

Please allow a range or multiple IP Addresses for bastion access in place of a string. We have a use case where we want bastion access to be enabled from a couple of different networks but looks like it is not possible atm.

### Potential Terraform Configuration

```hcl
variable "oci_base_bastion" {
  type = object({
    availability_domain              = number
    # bastion_access                 = string 
    bastion_access                   = list
....... 
```

**Comment by hyder** [comment]
Amazing, we just had the same request for OKE cluster access. Would you be willing to contribute to this?
