### ISSUE TITLE
[Feature] OCI Bastion support

### ISSUE THREAD

**Issue by denismakogon** [oracle-terraform-modules/terraform-oci-bastion#34]
At this moment this module supports only bastion host (also known as jump-host), but it doesn't support OCI Bastion. It would be great to support that as well and have bastion host + OCI Bastion resources created altogether to make cluster access only possible via OCI Bastion managed SSH session and bastion/operator host.

**Comment by karthicgit** [comment]
@hyder I talked with Denis he wanted bastion service for accessing OKE private cluster .

**Comment by hyder** [comment]
This has to be implemented in higher level Terraform modules.
