### ISSUE TITLE
Dynamic group creation in non-home region

### ISSUE THREAD

**Issue by sivachunduru** [oracle-terraform-modules/terraform-oci-bastion#45]
While the creation of bastion, if the non-home region is given as input, it throws an error to execute the dynamic group CREATE, UPDATE, DELETE commands in home region.

**Comment by hyder** [comment]
As discussed, you need to create 2 providers: https://github.com/oracle-terraform-modules/terraform-oci-bastion/tree/main/examples:

- 1 for the region where you'll create the bastion
- 1 for the tenancy's home region
